"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { analyze, sampleSize, validateDraft, type Counts, type Draft, type Guardrail } from "../lib/experiment-engine";

const STORE = "variant-experiments-v1";
const blankCounts: Counts = {controlVisitors:0,controlConversions:0,treatmentVisitors:0,treatmentConversions:0};
const percent = (n: number | null | undefined) => n == null ? "—" : `${(n*100).toFixed(2)}%`;

export default function Home() {
  const [drafts,setDrafts]=useState<Draft[]>([]);
  const [ready,setReady]=useState(false);
  const storageValid=useRef(true);
  const [selected,setSelected]=useState("");
  const [view,setView]=useState<"Experiments"|"Knowledge base">("Experiments");
  const [query,setQuery]=useState("");
  const [status,setStatus]=useState("");
  const [creating,setCreating]=useState(false);
  const [proposal,setProposal]=useState<{hypothesis:string;primaryMetric:string;guardrailMetrics:string[];provider:string}|null>(null);
  const [planning,setPlanning]=useState(false);
  const [form,setForm]=useState({name:"",hypothesis:"",audience:"",metric:"Conversion rate",baseline:"10",mde:"20"});
  const [counts,setCounts]=useState<Counts>(blankCounts);
  const [guardrail,setGuardrail]=useState({name:"",control:"",treatment:"",maxRegression:"",direction:"higher" as "higher"|"lower"});
  useEffect(()=>{
    const timer=setTimeout(()=>{
    try {const raw=window.localStorage.getItem(STORE);if(raw){const parsed:unknown=JSON.parse(raw);if(!Array.isArray(parsed)||parsed.length>200)throw Error("Invalid saved experiment collection.");setDrafts(parsed.map(validateDraft));}}
    catch {storageValid.current=false;setStatus("Saved workspace could not be loaded. Original data is preserved; import a valid exported report to recover it.");}
    setReady(true);
    },0);
    return ()=>clearTimeout(timer);
  },[]);
  useEffect(()=>{if(ready&&storageValid.current){try{window.localStorage.setItem(STORE,JSON.stringify(drafts));}catch{queueMicrotask(()=>setStatus("Browser storage is unavailable or full. Export your report before leaving."));}}},[drafts,ready]);
  const current=drafts.find(d=>d.id===selected);
  const result=current?analyze(current.counts,current.guardrails,current.baseline,current.mde):null;
  const filtered=drafts.filter(d=>[d.name,d.hypothesis,d.metric,d.audience,d.decision].join(" ").toLowerCase().includes(query.toLowerCase()));
  function patch(values:Partial<Draft>){setDrafts(rows=>rows.map(d=>d.id===selected?{...d,...values}:d));}
  function inspect(d:Draft){setSelected(d.id);setCounts({...d.counts});setCreating(false);setStatus("");}
  function exportData(){const blob=new Blob([JSON.stringify({version:1,experiments:drafts},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="variant-experiment-evidence.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function importData(file:File){try{if(file.size>1_000_000)throw Error("Import is limited to 1 MB.");const data=JSON.parse(await file.text());if(data.version!==1||!Array.isArray(data.experiments)||data.experiments.length>200)throw Error("Invalid exported report.");const rows:Draft[]=data.experiments.map(validateDraft);if(new Set(rows.map(d=>d.id)).size!==rows.length)throw Error("Report has duplicate experiment IDs.");const merged=[...drafts.filter(d=>!rows.some(r=>r.id===d.id)),...rows];if(merged.length>200)throw Error("Workspace is limited to 200 experiments; export before starting a separate workspace.");storageValid.current=true;setDrafts(merged);setStatus(`Imported ${rows.length} experiments. Matching IDs were updated.`);}catch(e){setStatus(e instanceof Error?e.message:"Import failed.");}}
  async function propose(){setPlanning(true);try{const response=await fetch("/api/ai/design",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({goal:form.hypothesis,productArea:form.name,audience:form.audience})});const data=await response.json();if(!response.ok)throw Error(data.error);setProposal({...data.design,provider:data.provider});setStatus("Planning proposal ready. Review it before using it; it does not validate your hypothesis.");}catch(e){setStatus(e instanceof Error?e.message:"Planning request failed.");}finally{setPlanning(false);}}
  let planned: number|undefined;
  try{planned=sampleSize(Number(form.baseline)/100,Number(form.mde)/100);}catch{/* Form validation occurs on save. */}
  return <main className="variant-lab"><header className="lab-header"><Link className="lab-brand" href="/">Variant<span>Experiment decision workspace</span></Link><div><button onClick={exportData}>Export workspace</button><label className="lab-import">Import report<input type="file" accept=".json" onChange={e=>{const file=e.target.files?.[0];if(file)void importData(file);e.target.value="";}}/></label><button className="lab-primary" onClick={()=>{setCreating(true);setSelected("");setProposal(null);}}>New experiment</button></div></header>
    <section className="lab-intro"><p className="lab-eyebrow">EVIDENCE BEFORE EXPANSION</p><h1>Design. Measure. Decide.</h1><p>A real local workflow from experiment hypothesis to saved readout. Enter your own counts and guardrails; every recommendation is calculated from that evidence.</p><p className="lab-note">Workspace data is stored in this browser. Rollout is a recorded plan, not a production feature flag. Model-assisted planning is optional.</p></section>
    <div role="status" aria-live="polite" className="lab-status">{status}</div>
    <section className="lab-stats"><article><span>Saved experiments</span><strong>{drafts.length}</strong></article><article><span>Pending reviews</span><strong>{drafts.filter(d=>d.decision==="Pending").length}</strong></article><article><span>Ship decisions</span><strong>{drafts.filter(d=>d.decision==="Ship").length}</strong></article><article><span>Hold / rollback</span><strong>{drafts.filter(d=>["Hold","Rollback"].includes(d.decision)).length}</strong></article></section>
    <div className="lab-layout"><aside className="lab-panel"><nav aria-label="Workspace views">{(["Experiments","Knowledge base"] as const).map(v=><button aria-pressed={v===view} key={v} onClick={()=>setView(v)}>{v}</button>)}</nav><label htmlFor="search">Search hypotheses, metrics and decisions</label><input id="search" value={query} onChange={e=>setQuery(e.target.value)}/><h2>{view==="Experiments"?"Experiment portfolio":"Saved learning"}</h2>{!ready?<p>Loading your local workspace…</p>:!filtered.length?<p>No matching saved experiments. Create an experiment or import an exported report.</p>:filtered.filter(d=>view!=="Knowledge base"||d.decision!=="Pending").map(d=><button className={selected===d.id?"lab-experiment selected":"lab-experiment"} key={d.id} onClick={()=>inspect(d)}><strong>{d.name}</strong><span>{d.metric} · {d.decision}</span><small>{d.audience}</small></button>)}{view==="Knowledge base"&&!filtered.some(d=>d.decision!=="Pending")&&<p>Log a review decision to add an evidence-backed learning record.</p>}</aside>
    <div>{creating&&<section className="lab-panel"><h2>Design a measurable experiment</h2><form onSubmit={e=>{e.preventDefault();try{if(drafts.length>=200)throw Error("Workspace is limited to 200 experiments.");const draft=validateDraft({id:crypto.randomUUID(),name:form.name,hypothesis:form.hypothesis,audience:form.audience,metric:form.metric,baseline:Number(form.baseline)/100,mde:Number(form.mde)/100,counts:{...blankCounts},guardrails:[],decision:"Pending",rollout:0,createdAt:new Date().toISOString()});setDrafts(rows=>[...rows,draft]);inspect(draft);setStatus("Draft saved. Add observed counts and guardrails for review.");}catch(error){setStatus(error instanceof Error?error.message:"Invalid draft.");}}}>
      {([['name','Experiment name'],['hypothesis','Testable hypothesis'],['audience','Target audience'],['metric','Primary conversion metric']] as const).map(([key,label])=><label key={key}>{label}{key==="hypothesis"?<textarea required maxLength={4000} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input required maxLength={4000} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}
      <div className="lab-columns"><label>Baseline conversion (%)<input type="number" step="any" required min="0.001" max="99.99" value={form.baseline} onChange={e=>setForm({...form,baseline:e.target.value})}/></label><label>Minimum useful relative lift (%)<input type="number" step="any" required min="0.001" value={form.mde} onChange={e=>setForm({...form,mde:e.target.value})}/></label></div><p>Planned sample: <strong>{planned?.toLocaleString()??"Enter a valid baseline and MDE"} users per arm</strong>. 50/50 assignment, 5% two-sided significance, 80% approximate power. Freeze the plan before viewing outcomes.</p><button className="lab-primary">Save draft</button><button type="button" disabled={planning||form.hypothesis.trim().length<10} onClick={()=>void propose()}>{planning?"Planning…":"Suggest a measurement plan"}</button></form>
      {proposal&&<article className="lab-proposal"><h3>{proposal.provider==="local-outline"?"Local planning outline":"Model-generated proposal"}</h3><p>{proposal.hypothesis}</p><p>Primary: {proposal.primaryMetric}</p><p>Review guardrails: {proposal.guardrailMetrics.join(" · ")}</p><button onClick={()=>setForm({...form,hypothesis:proposal.hypothesis,metric:proposal.primaryMetric})}>Use reviewed proposal</button></article>}</section>}
      {current&&result&&<><section className="lab-panel"><p className="lab-eyebrow">EXPERIMENT READOUT</p><h2>{current.name}</h2><p>{current.hypothesis}</p><p>{current.audience} · {current.metric} · created {new Date(current.createdAt).toLocaleDateString()}</p><p>Baseline {percent(current.baseline)} · target relative lift {percent(current.mde)} · planned users per arm {result.targetPerArm.toLocaleString()}</p><h3>Enter observed results</h3><form onSubmit={e=>{e.preventDefault();try{analyze(counts,current.guardrails,current.baseline,current.mde);patch({counts:{...counts},decision:"Pending"});setStatus("Counts saved. Review the computed recommendation.");}catch(error){setStatus(error instanceof Error?error.message:"Invalid counts.");}}}><div className="lab-columns">{(Object.keys(blankCounts) as (keyof Counts)[]).map(key=><label key={key}>{key.replace(/([A-Z])/g," $1")}<input type="number" min="0" step="1" required value={counts[key]} onChange={e=>setCounts({...counts,[key]:Number(e.target.value)})}/></label>)}</div><button>Save observed counts</button></form>
      <h3>Guardrail limits</h3><p>Use each metric’s native units. “Higher is better” detects a decrease; “Lower is better” detects an increase.</p>{current.guardrails.map((g,i)=><p key={i}><strong>{g.name}</strong>: {g.control} control → {g.treatment} treatment, allowed regression {g.maxRegression} <button onClick={()=>patch({guardrails:current.guardrails.filter((_,j)=>j!==i),decision:"Pending"})}>Remove {g.name}</button></p>)}
      <form onSubmit={e=>{e.preventDefault();try{const g:Guardrail={name:guardrail.name,control:Number(guardrail.control),treatment:Number(guardrail.treatment),maxRegression:Number(guardrail.maxRegression),direction:guardrail.direction};analyze(current.counts,[...current.guardrails,g],current.baseline,current.mde);patch({guardrails:[...current.guardrails,g],decision:"Pending"});setGuardrail({name:"",control:"",treatment:"",maxRegression:"",direction:"higher"});setStatus("Guardrail saved.");}catch(error){setStatus(error instanceof Error?error.message:"Invalid guardrail.");}}}><label>Guardrail name<input value={guardrail.name} required onChange={e=>setGuardrail({...guardrail,name:e.target.value})}/></label><div className="lab-columns">{(['control','treatment','maxRegression'] as const).map(key=><label key={key}>{key==='maxRegression'?'Allowed regression':key}<input type="number" step="any" min="0" required value={guardrail[key]} onChange={e=>setGuardrail({...guardrail,[key]:e.target.value})}/></label>)}<label>Preferred direction<select value={guardrail.direction} onChange={e=>setGuardrail({...guardrail,direction:e.target.value as 'higher'|'lower'})}><option value="higher">Higher is better</option><option value="lower">Lower is better</option></select></label></div><button>Add guardrail</button></form></section>
      <section className="lab-panel"><h2>{result.recommendation}: computed review recommendation</h2><p>{result.reason}</p>{result.status==="Analyzed"&&<><div className="lab-stats"><article><span>Control conversion</span><strong>{percent(result.controlRate)}</strong></article><article><span>Treatment conversion</span><strong>{percent(result.treatmentRate)}</strong></article><article><span>Absolute lift</span><strong>{percent(result.absoluteLift)}</strong></article><article><span>Two-sided p-value</span><strong>{result.pValue?.toFixed(4)??"Sparse sample"}</strong></article></div><p>95% absolute-lift interval: {result.confidenceInterval95?result.confidenceInterval95.map(percent).join(" to "):"Not valid for sparse results"}. Relative lift: {percent(result.relativeLift)}.</p><ul>{result.guardrails.map(g=><li key={g.name}>{g.name}: {g.breached?"BREACHED":"Within entered limit"} (regression {g.regression.toFixed(3)}, limit {g.maxRegression})</li>)}</ul><ul>{result.limitations?.map(text=><li key={text}>{text}</li>)}</ul></>}
      <h3>Record your decision</h3><div className="lab-decisions">{['Ship','Hold','Iterate','Rollback'].map(decision=><button key={decision} aria-pressed={current.decision===decision} onClick={()=>{patch({decision});setStatus(`Human decision saved: ${decision}.`);}}>{decision}</button>)}</div><label>Planned rollout: {current.rollout}%<input type="range" min="0" max="100" value={current.rollout} onChange={e=>patch({rollout:Number(e.target.value)})}/></label><p>Decisions and rollout plans remain inspectable in the exported report. Changing these controls does not execute a release.</p></section></>}
      {!creating&&!current&&<section className="lab-panel"><h2>Start with a real question.</h2><p>Create an experiment, enter its predeclared baseline and minimum useful effect, then record observations. The knowledge base contains your saved decisions rather than invented historical outcomes.</p><button className="lab-primary" onClick={()=>setCreating(true)}>Create your first experiment</button></section>}
    </div></div>
  </main>;
}
